apiVersion: v1
kind: ServiceAccount
metadata:
  name: operate-workflow-sa
  annotations:
    workflows.argoproj.io/service-account-token.name: operate-workflow-sa.service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: operate-workflow-sa.service-account-token
  annotations:
    kubernetes.io/service-account.name: operate-workflow-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operate-workflow-role
rules:
  - apiGroups:
      - argoproj.io
    verbs:
      - "*"
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operate-workflow-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operate-workflow-role
subjects:
  - kind: ServiceAccount
    name: operate-workflow-sa
